# SOPS configuration
# Update AGE_PUBLIC_KEY with your key from .age/key.pub
creation_rules:
  - path_regex: .*\.enc\.yaml$
    encrypted_regex: "^(data|stringData)$"
    age: AGE_PUBLIC_KEY
  - path_regex: secrets/.*\.yaml$
    encrypted_regex: "^(data|stringData)$"
    age: AGE_PUBLIC_KEY

